name: mayo_flutter
description: "official mayo flutter app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  go_router: ^14.6.2
  flutter_dotenv: ^5.2.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  flutter_screenutil: ^5.9.3
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter_svg: ^2.0.17
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 600
