name: mayo_flutter
description: "official mayo flutter app"
publish_to: "none"
version: 2.0.6+6

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  go_router: ^14.6.2
  flutter_dotenv: ^5.2.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  flutter_screenutil: ^5.9.3
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter_svg: ^2.0.17
  google_sign_in: ^6.2.2
  flutter_native_splash: ^2.4.4
  intl: ^0.19.0
  kakao_map_plugin: ^0.3.5
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.4
  sign_in_with_apple: ^6.1.4
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true # 안드로이드 플랫폼에 런처 아이콘 적용 여부
  ios: true # iOS 플랫폼에 런처 아이콘 적용 여부
  image_path: "assets/icons/appstore.png" # 런처 아이콘으로 사용할 이미지 경로
  adaptive_icon_background: "#000000" # 안드로이드 적응형 아이콘의 배경색 (검정색)
  adaptive_icon_foreground: "assets/icons/appstore.png" # 안드로이드 적응형 아이콘의 전경 이미지 경로
  min_sdk_android: 21 # 안드로이드 최소 SDK 버전 (API 21(Android 5.0) 이상)

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
          weight: 600
