name: flutter-ci
on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: "20250103"
          architecture: x64
      - run: flutter pub get
      - run: |
          echo "API_URL=$API_URL" >> .env
        env:
          DB_URL: ${{ secrets.API_URL }}
      - run: flutter analyze

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: "20250103"
          architecture: x64
      - run: flutter pub get
      - run: |
          echo "API_URL=$API_URL" >> .env
        env:
          DB_URL: ${{ secrets.API_URL }}
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - run: flutter build apk
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
